/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adrianthehacker.intro_to_javafx;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;


public class App extends Application {
    private int windowWidth = 600; 
    private int windowHeight = 900;

    Button button;

    @Override
    public void start(Stage stage) {
        button = new Button();
        button.setText("Hello, World");
        button.setOnAction(e -> buttonClick());

        BorderPane pane = new BorderPane();
        pane.setCenter(button);

        Scene scene = new Scene(pane, this.windowWidth, this.windowHeight);

        stage.setScene(scene);
        stage.setTitle("CLickable Button");
        stage.show();
    }

    public void buttonClick() {
        System.out.println("Button Clicked");
    }

    public static void main(String[] args) {
        launch();
    }
}